title: Merlin Wassermann - Freier Journalist
author:
  name: Merlin Wassermann
  email: merlin.wassermann@gmail.com

description: >
  Ich bin einer freier Journalist, BLABLA

theme: minima
  remote_theme: jekyll/minima


show_excerpts: false

minima:
  skin: classic
  
  date_format: "%b-%d-%Y"

